name: Test doc snippets

on: push

jobs:
  build-and-test:
    name: Build package and test snippets
    runs-on: 'ubuntu-latest'
    services:
      hub:
        image: selenium/hub:3.141.59-gold
      firefox:
        image: selenium/node-chrome:3.141.59-gold
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dash
        run: python -m pip install -r requirements-dev.txt
      - name: Build dash-bootstrap-components
        run: npm run build
      - name: Install R dependencies from cran2deb4ubuntu
        run: |
          sudo add-apt-repository ppa:c2d4u.team/c2d4u4.0+
          sudo apt-get update
          sudo apt-get install r-recommended r-cran-dash
      - name: Install R package
        run: sudo R CMD INSTALL .
      - name: Run R test
        run: Rscript app.R
